version: '3'

services:
  database:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: apiv2
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    
  api:
    image: valentinochiappanni07/apiv4:v1.0.0
    ports:
      - "3005:3000"
    depends_on:
      - database